### ISSUE TITLE
CPU support

### ISSUE THREAD

**Issue by 71coder** [ParrotXray/ASUS-B85M-G-Haswell-OC-Hackintosh#1]
Hello, can this support E3 1231v3/1241v3？

**Comment by ParrotXray** [comment]
> 你好，這個可以支持E3 1231v3/1241v3嗎？

Yes, the motherboard supports all Haswell 1150 CPUs, including E3 series

**Comment by ParrotXray** [comment]
> Hello, can this support E3 1231v3/1241v3？

Yes, the motherboard supports all Haswell 1150 CPUs, including E3 series
