### ISSUE TITLE
睡眠唤醒问题

### ISSUE THREAD

**Issue by BigGrassDog** [ParrotXray/ASUS-B85M-G-Haswell-OC-Hackintosh#3]
大佬你好，有没有出现过偶尔长时间睡眠唤醒后电脑变的很卡的问题？硬盘灯常亮不闪烁。

**Comment by ParrotXray** [comment]
> 大佬你好，有没有出现过偶尔长时间睡眠唤醒后电脑变的很卡的问题？硬盘灯常亮不闪烁。

我之前用讓他睡了一個晚上都沒有問題，燈常亮到是很常看到，但是也沒怎麼樣就沒在意了

**Comment by BigGrassDog** [comment]
感谢大佬的回复。经过多日的实验，昨天偶然发现进黑苹果系统时禁止挂载windows的两个ntfs硬盘貌似解决了这个问题。目前持续测试尝试重现这个问题中。
