### ISSUE TITLE
Above 4G decoding

### ISSUE THREAD

**Issue by pumpkin-nbc** [ParrotXray/ASUS-B85M-G-Haswell-OC-Hackintosh#4]
想问下关于这个块主板是否能够开启 Above 4G decoding
从黑苹果站点看到可以开启

**Comment by ParrotXray** [comment]
> 想问下关于这个块主板是否能够开启 Above 4G decoding
> 
> 从黑苹果站点看到可以开启

不用，也沒這個選項，這功能好像只會在100系以上的主板才有，照我上面寫的改就行了
