### ISSUE TITLE
(請益)是否支援HEVC 硬解

### ISSUE THREAD

**Issue by jimmy0800** [ParrotXray/ASUS-B85M-G-Haswell-OC-Hackintosh#5]
你好，我使用與你相同主機板搭配I5-4440 CPU 以及技嘉 RX580 8G 顯示卡
想請問兩個問題，我使用VideoProc 檢測好像不支援HEVC 硬解 這樣是正常的嗎?
另外，不論我使用那一版本BIOS Launch CSM處於Disabled狀態都會遇到蜂鳴器發出一長三短提示音
且在進入系統前面 完全看不到任何畫面，不知道你有遇過這問題嗎?

**Comment by ParrotXray** [comment]
> 你好，我使用與你相同主機板搭配I5-4440 CPU 以及技嘉 RX580 8G 顯示卡 想請問兩個問題，我使用VideoProc 檢測好像不支援HEVC 硬解 這樣是正常的嗎? 另外，不論我使用那一版本BIOS Launch CSM處於Disabled狀態都會遇到蜂鳴器發出一長三短提示音 且在進入系統前面 完全看不到任何畫面，不知道你有遇過這問題嗎?

1. 我沒記錯的話硬解只有一個是支援的
2. 我之前也有遇過一長三短，我的原因為顯卡無法通過純UEFI的系統開機，但我的顯卡是雙BIOS的，切到另一個就沒事，技嘉的卡我倒是只有用過一次，所以不清楚
